### ISSUE TITLE
Are there any examples for streaming the output of a command?

### ISSUE THREAD

**Issue by carterbryden** [bitcrowd/sshkit.ex#150]
That is, if I do SSHKit.run("wget someaddress.com/file"), can we stream the output as it comes in rather than wait for it to all completely finish?

**Comment by pmeinhardt** [comment]
Great question! 💚

If you look at [`SSHKit.SSH.run/3`](https://github.com/bitcrowd/sshkit.ex/blob/8e8edceaee6432b544f2acea4ea875c7dce4ca1c/lib/sshkit/ssh.ex#L96-L143), it allows you to pass a `:fun` option (for maximum fun 😁).
The default for that is to [`capture/2`](https://github.com/bitcrowd/sshkit.ex/blob/8e8edceaee6432b544f2acea4ea875c7dce4ca1c/lib/sshkit/ssh.ex#L145-L160) all of the output into a list.

You might be able to do streaming with this lower-level API by providing a custom function there for now? 🤔 

Otherwise, I've actually been thinking about changing SSHKit's interface to behave more similar to that of [mint](https://github.com/ericmj/mint), i.e. the process that calls `SSHKit.run/2` would just `receive` messages as a result.

Happy if you could provide feedback on both a potential solution with the current API and maybe thoughts on the idea of a mint-like interface. ✌️

**Comment by pmeinhardt** [comment]
There has not been any activity/feedback on this in more than a year, so I will go ahead and close this.
Please feel free to re-open, Carter, in case we can be of help.

In the meanwhile, we're working on a new version of the package which should make it easier to stream output directly. You can follow the work in this PR if you're interested: https://github.com/bitcrowd/sshkit.ex/pull/164

There are some working examples showcasing the new APIs. It's still a work-in-progress, but might give you some ideas:
https://github.com/bitcrowd/sshkit.ex/tree/v1/examples

✌️
