### ISSUE TITLE
SSHKit.SSH.connect fails with {:error, 'User interaction is not allowed'} if HashKnownHosts is set to yes

### ISSUE THREAD

**Issue by MisterToolbox** [bitcrowd/sshkit.ex#85]
SSHKit.SSH.connect fails with {:error, 'User interaction is not allowed'} if HashKnownHosts is set to yes in /etc/ssh/ssh_config. 'yes' is the default setting in Ubuntu 16+

Setting the line to 'no' and restarting the SSH service clears the problem and connections can than be established.

**Comment by klappradla** [comment]
Hey @MisterToolbox thanx for reporting 🙏 

Sound interesting and is definitely something we should look into - especially given the fact that SSHKit apparently isn't _"compatible"_ with defaults here 🤔 
However, since we're currently fully occupied with client-work, we won't find the time to dig into this immediately 😿 

But if you have any suggestions on how to handle / fix this or even know how to do it in the code, any information or PRs are super welcome 🤗 Just let us know if there are any obstacles where we can help you.

**Comment by klappradla** [comment]
Hey @MisterToolbox 👋 

sorry it took me so long to get back to this 🙈 

I could reproduce your error and have several "solutions"™ for it. I could however not yet come up with an approach to "fix" this in the `SSHKit` code itself 🤔  (it's technically speaking not a bug...)

Here's my approach:

### Setup
I build a Ubuntu 16.04 container running an ssh service and a `root` user with password `secret`. Here's the `Dockerfile`
```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:secret' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
```

And you're right, `/etc/ssh/ssh_config` has
```
HashKnownHosts yes
```

### Connecting

*(I retrieve the containers port via `docker ps` - let's just say it's `1234` here)*

```elixir
SSHKit.SSH.connect "localhost", port: 1234, user: "root", password: "secret"
```
**☝️  connecting fails if the machine is not already listed in your `known_hosts` file**
If you try to connect with Erlang's `:ssh` directly you'll get a prompt for adding the host to your list of known hosts that then blocks the command and `iex` forever 😞 

So the problem is: adding a host to the list of known hosts requires a user interaction that we're not capable of doing, neither in Erlang nor in Elixir.

### Solutions

1. Add the host to your machine's `known_hosts` file upfront
2. Allow any host (`silently_accept_hosts` option)
    ```elixir
    SSHKit.SSH.connect("localhost",
      port: 1234,
      user: "root",
      password: "secret",
      silently_accept_hosts: true)
    ```
    ☝️  This works fine without having to change the default `ssh_config` on Ubuntu.
3. Remove the `HashKnownHosts` line from the host's config *(as you did)*

So I guess solution nr 2 would be best for you 🤔 
I however don't want to set this as a default in `SSHKit`, plus for now don't see any other way of "fixing" this in code.

What do you think? Can you work with this? Or do you even have a better solution? Happy to hear about it 🎉

**Comment by MisterToolbox** [comment]
Thanks for taking the time to check it out, @klappradla!

Given the way my environment's set up, I'm sticking with the third option for now. Wouldn't be surprised to see this accounted for upstream in the Erlang's `:ssh` and have the fingerprints compared in there, at which point it'll be a non-issue in SSHKit.

**Comment by klappradla** [comment]
Ok cool!
If you still come up with different solutions - always happy to hear them 🤓

**Comment by JediLuke** [comment]
Is there any way of getting this to wotk with `SSHKit.SCP`?
