### ISSUE TITLE
Check out Mox for mockin in unit tests

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/sshkit.ex#93]
Maybe Mox could be a useful package to use in our unit tests?

- https://hexdocs.pm/mox/Mox.html
- https://github.com/plataformatec/mox

cc @klappradla, @tessi

**Comment by klappradla** [comment]
Looks indeed very promising @pmeinhardt 👀 

It's also along the lines of what we already introduced with dependency injecting *(I'm not 100% sure if that's how it's really called...)* certain modules in order to **not** have the tests call the underlying Erlang modules.
However, I feel that this can only be applied broadly if we also take care of #90 (could eventually be done at the same time) - don't you think 🤔

**Comment by pmeinhardt** [comment]
@klappradla, took Mox for a spin on my current project at work and it turned out to be quite useful. A benefit for SSHKit would be that we can define expected calls and provided results more fine-grained than with the current mocking approach. I'll see if I can whip up a PR anytime soon so we can see if we'd like to use it for SSHKit with a concrete example.

**Comment by pmeinhardt** [comment]
Done! Now we have a chance of properly unit-testing `SCP.{Download, Upload}` 🙌
